# Generated by Django 5.0.14 on 2026-08-07 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0002_add_fecha_nacimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudsocio',
            name='razon',
            field=models.TextField(blank=True, default='', verbose_name='Razón de unirse al club'),
        ),
    ]
