# Generated by Django 5.0.14 on 2026-08-09 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0003_solicitudsocio_razon'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudsocio',
            name='apellido_materno',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Apellido materno'),
        ),
        migrations.AddField(
            model_name='solicitudsocio',
            name='apellido_paterno',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Apellido paterno'),
        ),
        migrations.AddField(
            model_name='solicitudsocio',
            name='carnet_ci',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='CI / Carnet'),
        ),
        migrations.AddField(
            model_name='solicitudsocio',
            name='carnet_complemento',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Complemento CI'),
        ),
        migrations.AlterField(
            model_name='solicitudsocio',
            name='apellido',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Apellidos'),
        ),
    ]
