# Generated by Django 5.0.14 on 2026-08-06 23:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Socio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombres')),
                ('apellido', models.CharField(max_length=150, verbose_name='Apellidos')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('telefono', models.CharField(blank=True, default='', max_length=20, verbose_name='Teléfono')),
                ('ciudad', models.CharField(blank=True, default='', max_length=150, verbose_name='Ciudad')),
                ('direccion', models.CharField(blank=True, default='', max_length=250, verbose_name='Dirección')),
                ('fecha_ingreso', models.DateField(auto_now_add=True, verbose_name='Fecha de ingreso')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=20)),
                ('recibio_souvenir', models.BooleanField(default=False, verbose_name='Recibió souvenir')),
                ('observacion', models.TextField(blank=True, default='', verbose_name='Observación')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='socio_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Socio',
                'verbose_name_plural': 'Socios',
                'ordering': ['-fecha_ingreso', 'apellido', 'nombre'],
            },
        ),
    ]
