# Generated by Django 5.0.14 on 2026-08-09 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0003_socio_apellido_materno_socio_apellido_paterno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socio',
            name='carnet_complemento',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Complemento CI'),
        ),
    ]
