# Generated by Django 5.0.14 on 2026-08-09 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0004_alter_socio_carnet_complemento'),
    ]

    operations = [
        migrations.AddField(
            model_name='socio',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento'),
        ),
        migrations.AddField(
            model_name='socio',
            name='razon',
            field=models.TextField(blank=True, default='', verbose_name='Razón de ingreso'),
        ),
    ]
