# Generated by Django 5.0.14 on 2026-08-09 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0005_socio_fecha_nacimiento_socio_razon'),
    ]

    operations = [
        migrations.AddField(
            model_name='socio',
            name='codigo_socio',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True, verbose_name='Código de socio'),
        ),
    ]
