# Generated by Django 5.0.14 on 2026-08-06 23:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('socios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SouvenirEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_entrega', models.DateField(auto_now_add=True, verbose_name='Fecha de entrega')),
                ('observacion', models.TextField(blank=True, default='', verbose_name='Observación')),
                ('entregado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entregas_souvenir', to=settings.AUTH_USER_MODEL)),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas_souvenir', to='socios.socio')),
            ],
            options={
                'verbose_name': 'Entrega de souvenir',
                'verbose_name_plural': 'Entregas de souvenirs',
                'ordering': ['-fecha_entrega'],
            },
        ),
    ]
