# Generated by Django 5.0.14 on 2026-08-07 01:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('souvenirs', '0002_souvenir'),
    ]

    operations = [
        migrations.AddField(
            model_name='souvenirentrega',
            name='souvenir',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entregas', to='souvenirs.souvenir'),
        ),
    ]
