# Generated by Django 5.0.14 on 2026-08-09 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
        ('souvenirs', '0003_souvenirentrega_souvenir'),
    ]

    operations = [
        migrations.AddField(
            model_name='souvenirentrega',
            name='evento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entregas_souvenir', to='eventos.evento'),
        ),
    ]
