# Generated by Django 5.0.14 on 2026-08-09 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
        ('souvenirs', '0004_souvenirentrega_evento'),
    ]

    operations = [
        migrations.AddField(
            model_name='souvenir',
            name='evento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='souvenirs', to='eventos.evento'),
        ),
    ]
